version: "3.7"

services:
  product_db:
    image: postgres
    container_name: product_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data